### ISSUE TITLE
How to do this in Galaxy (Windows + Minikube)?

### ISSUE THREAD

**Issue by jianlianggao** [TailorDev/galaxy-tourbuilder#13]
Hi,
How can this be done in  Galaxy running on Windows with minikube?

Thanks,

Best regards,
Jianliang

**Comment by willdurand** [comment]
Hi @jianlianggao, I am not sure to understand. What do you mean? This tool is useful to create Galaxy tours, but then you have to install them into your Galaxy instance. It seems you have to copy your YAML files (that can be created by this browser extension) to `galaxy_root/config/plugins/tours/`, and then the tours should be available into your instance.

**Comment by bgruening** [comment]
@jianlianggao what do you mean by `this`? Tourbilder is browser plugin you can use to create Galaxy tours interactively.

**Comment by jianlianggao** [comment]
Thank you very much @willdurand  I'll give a go.
Thanks @bgruening , William answered my question. I'll try.
