### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by willdurand** [TailorDev/galaxy-tourbuilder#5]
I need more feedback before releasing `1.0.0`. I have tested the extension on all claimed supported browsers (Chrome, Opera, Firefox) and it works as intended.

The plan is to have a stable first release this summer, so that I can release and publish this extension in all app stores. TailorDev will cover the expenses (if any).

Now waiting for feedback 🙏

**Comment by willdurand** [comment]
Fixed. Version [1.0.0](https://github.com/TailorDev/galaxy-tourbuilder/releases/tag/1.0.0) has been released and is under submission on all stores.

**Comment by jibe-b** [comment]
Amazing job guys, thanks so much!
